"""add_is_correct_to_uploads

Revision ID: 09428d862632
Revises: 09a18509cc1d
Create Date: 2026-03-26 11:49:46.865393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09428d862632'
down_revision: Union[str, None] = '09a18509cc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'is_correct')
    # ### end Alembic commands ###
