"""add_is_checked_to_uploads

Revision ID: 09a18509cc1d
Revises: 1d54d4d124cc
Create Date: 2026-03-21 14:23:37.532918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a18509cc1d'
down_revision: Union[str, None] = '1d54d4d124cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
