"""add_is_correct

Revision ID: 164a211c60cc
Revises: 09428d862632
Create Date: 2026-03-26 21:21:00.897002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164a211c60cc'
down_revision: Union[str, None] = '09428d862632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('firstname', sa.String(length=128), nullable=False))
    op.add_column('teams', sa.Column('lastname', sa.String(length=128), nullable=False))
    op.drop_index('ix_teams_name', table_name='teams')
    op.create_index(op.f('ix_teams_firstname'), 'teams', ['firstname'], unique=False)
    op.create_index(op.f('ix_teams_lastname'), 'teams', ['lastname'], unique=False)
    op.drop_column('teams', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_lastname'), table_name='teams')
    op.drop_index(op.f('ix_teams_firstname'), table_name='teams')
    op.create_index('ix_teams_name', 'teams', ['name'], unique=True)
    op.drop_column('teams', 'lastname')
    op.drop_column('teams', 'firstname')
    # ### end Alembic commands ###
