"""add_is_checked_to_uploads

Revision ID: 1d54d4d124cc
Revises: 0feb775a5cbd
Create Date: 2026-03-21 14:22:19.678228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d54d4d124cc'
down_revision: Union[str, None] = '0feb775a5cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('is_checked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('uploads', sa.Column('checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'checked_at')
    op.drop_column('uploads', 'is_checked')
    # ### end Alembic commands ###
