"""add_first_last_name_to_teams

Revision ID: 62ad01dc3d89
Revises: 164a211c60cc
Create Date: 2026-03-27 12:23:22.996327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ad01dc3d89'
down_revision: Union[str, None] = '164a211c60cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('teams', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.add_column('teams', sa.Column('name', sa.String(length=256), nullable=False))
    op.drop_index('ix_teams_firstname', table_name='teams')
    op.drop_index('ix_teams_lastname', table_name='teams')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.drop_column('teams', 'firstname')
    op.drop_column('teams', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('lastname', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('firstname', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_index('ix_teams_lastname', 'teams', ['lastname'], unique=False)
    op.create_index('ix_teams_firstname', 'teams', ['firstname'], unique=False)
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'last_name')
    op.drop_column('teams', 'first_name')
    # ### end Alembic commands ###
